"""Tests for raw G-code header metadata used by the File Manager."""

from backend.app.api.routes.library import extract_gcode_metadata


def test_extracts_elegoo_initial_filament_from_header():
    metadata = extract_gcode_metadata("; generated by Elegoo Slicer\n; initial_filament: PLA\nG28\n")

    assert metadata == {"filament_type": "PLA"}


def test_extracts_orca_filament_type_from_header():
    metadata = extract_gcode_metadata("; generated by OrcaSlicer\n; filament_type = PETG\nG28\n")

    assert metadata == {"filament_type": "PETG"}


def test_normalizes_multimaterial_header_into_distinct_types():
    metadata = extract_gcode_metadata("; filament_type = PLA;PETG;PLA\nG28\n")

    assert metadata == {"filament_type": "PLA, PETG"}


def test_ignores_filament_markers_after_gcode_starts():
    metadata = extract_gcode_metadata("; generated by OrcaSlicer\nG28\n; filament_type = ABS\n")

    assert metadata == {}
