"""Tests for raw G-code header metadata used by the File Manager."""

from backend.app.api.routes.library import extract_gcode_metadata


def test_extracts_elegoo_initial_filament_after_startup_commands():
    metadata = extract_gcode_metadata(
        "; EXECUTABLE_BLOCK_START\n"
        "EXECUTABLE_OBJECT_DEFINE NAME=Kuma_Front_Flat.stp\n"
        "M73 P0 R335\n"
        "M106 S0\n"
        "; print date: 20240520\n"
        "; printer_model:Elegoo Centauri Carbon\n"
        ";initial_filament:PETG\n"
        ";LAYER:0\n"
    )

    assert metadata == {"filament_type": "PETG"}


def test_extracts_orca_filament_type_from_header():
    metadata = extract_gcode_metadata("; generated by OrcaSlicer\n; filament_type = PETG\nG28\n")

    assert metadata == {"filament_type": "PETG"}


def test_normalizes_multimaterial_header_into_distinct_types():
    metadata = extract_gcode_metadata("; filament_type = PLA;PETG;PLA\nG28\n")

    assert metadata == {"filament_type": "PLA, PETG"}


def test_ignores_filament_markers_after_first_layer():
    metadata = extract_gcode_metadata("; filament_type = PETG\n;LAYER:0\n; initial_filament: ABS\n")

    assert metadata == {"filament_type": "PETG"}
